//************************ 1st way - default excep msg **************************

class MyException extends Exception{                          //Checked Exception

	public MyException(){
		super("This is a user generated default exception message");
	}
}

class UserDefinedException{
	public static void main(String args[]){
		System.out.println("Program Execution started");
		try{
			throw new MyException( );
		}
		catch(MyException e){
			System.out.println("MyException caught : "+e.getMessage()); 
		}
		System.out.println("Program Executed Successfully");
	}	
}
/*
o/p:
Program Execution started
MyException caught : This is a user generated  default  exception message
Program Executed Successfully
*/


//****************************** 2nd way ********************************
/*
class MyException extends Exception{                          //Checked Exception
	
	String excpMsg;
	public MyException(){
		super("This is a user generated default exception message");
		excpMsg = "My exception msg"; 
	}
	public MyException(String msg){
		super(msg);
	}
}
class UserDefinedException{
	public static void main(String args[]){
		System.out.println("Program Execution started");
		try{
			throw new MyException("This is an exception generated by user");
		}
		catch(MyException e){
			System.out.println("MyException caught : "+e.getMessage()); 
		}
		System.out.println("Program Executed Successfully");
	}	
}
*/
/*
o/p:
Program Execution started
MyException caught : This is an exception generated by user
Program Executed Successfully
*/


